[platformio]
default_envs = genericSTM32F103RC

[env:genericSTM32F103RC]
platform = ststm32
board = genericSTM32F103RC
framework = arduino
board_build.mcu = stm32f103rct6
board_build.f_cpu = 72000000L
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
monitor_filters = time
build_flags =
  -D HAL_TIM_MODULE_ENABLED
