#!/usr/bin/env python3
"""Generate STM32, ROS 2 and Xacro configuration from config/robot_specs.yaml."""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "config" / "robot_specs.yaml"
HEADER_PATH = ROOT / "platformio_firmware" / "include" / "generated" / "RobotSpecs.h"
ROS_PATH = ROOT / "ros2_ws" / "src" / "moebius_base_driver" / "config" / "base_driver.yaml"
XACRO_PATH = ROOT / "ros2_ws" / "src" / "moebius_description" / "urdf" / "generated" / "robot_specs.xacro"


def load_specs() -> dict:
    with SPEC_PATH.open("r", encoding="utf-8") as stream:
        specs = yaml.safe_load(stream)
    required = ("robot", "motor", "encoder", "control", "communication", "battery")
    missing = [key for key in required if key not in specs]
    if missing:
        raise ValueError(f"Missing sections: {', '.join(missing)}")
    return specs


def derived(specs: dict) -> dict:
    robot = specs["robot"]
    motor = specs["motor"]
    encoder = specs["encoder"]
    counts = int(round(encoder["basic_ppr"] * encoder["quadrature_factor"] * motor["gear_ratio"]))
    circumference = math.pi * robot["wheel_diameter_m"]
    return {
        "counts_per_wheel_revolution": counts,
        "meters_per_tick": circumference / counts,
        "theoretical_max_speed_mps": motor["rated_output_rpm"] * circumference / 60.0,
        "half_wheelbase_m": robot["wheelbase_m"] / 2.0,
        "half_track_width_m": robot["track_width_m"] / 2.0,
    }


def render_header(specs: dict, values: dict) -> str:
    r, m, e, c, comm, b = (specs[k] for k in ("robot", "motor", "encoder", "control", "communication", "battery"))
    return f'''// AUTO-GENERATED by scripts/generate_robot_config.py. DO NOT EDIT.\n#pragma once\n\n#include <cstdint>\n\nnamespace robot_specs {{\nconstexpr float WHEEL_DIAMETER_M = {r['wheel_diameter_m']:.6f}f;\nconstexpr float WHEEL_RADIUS_M = {r['wheel_radius_m']:.6f}f;\nconstexpr float WHEELBASE_M = {r['wheelbase_m']:.6f}f;\nconstexpr float TRACK_WIDTH_M = {r['track_width_m']:.6f}f;\nconstexpr float HALF_WHEELBASE_M = {values['half_wheelbase_m']:.6f}f;\nconstexpr float HALF_TRACK_WIDTH_M = {values['half_track_width_m']:.6f}f;\nconstexpr float MAX_LINEAR_VELOCITY_MPS = {r['max_linear_velocity_mps']:.6f}f;\nconstexpr float MAX_LATERAL_VELOCITY_MPS = {r['max_lateral_velocity_mps']:.6f}f;\nconstexpr float MAX_ANGULAR_VELOCITY_RPS = {r['max_angular_velocity_rps']:.6f}f;\n\nconstexpr float MOTOR_RATED_OUTPUT_RPM = {m['rated_output_rpm']:.6f}f;\nconstexpr float GEAR_RATIO = {m['gear_ratio']:.6f}f;\nconstexpr std::uint16_t ENCODER_BASIC_PPR = {int(e['basic_ppr'])};\nconstexpr std::uint8_t ENCODER_QUADRATURE_FACTOR = {int(e['quadrature_factor'])};\nconstexpr std::uint32_t COUNTS_PER_WHEEL_REV = {values['counts_per_wheel_revolution']};\nconstexpr float METERS_PER_TICK = {values['meters_per_tick']:.9f}f;\nconstexpr float THEORETICAL_MAX_SPEED_MPS = {values['theoretical_max_speed_mps']:.6f}f;\n\nconstexpr float PID_KP = {c['pid_kp']:.6f}f;\nconstexpr float PID_KI = {c['pid_ki']:.6f}f;\nconstexpr float PID_KD = {c['pid_kd']:.6f}f;\nconstexpr std::uint32_t CONTROL_PERIOD_US = {int(c['control_period_us'])};\nconstexpr std::uint32_t FEEDBACK_PERIOD_MS = {int(c['feedback_period_ms'])};\nconstexpr std::uint32_t COMMAND_TIMEOUT_MS = {int(c['command_timeout_ms'])};\nconstexpr std::uint32_t ROS_UART_BAUD = {int(comm['baudrate'])};\n\nconstexpr float BATTERY_EMPTY_V = {b['empty_voltage']:.6f}f;\nconstexpr float BATTERY_FULL_V = {b['full_voltage']:.6f}f;\nconstexpr float BATTERY_CRITICAL_V = {b['critical_voltage']:.6f}f;\n}}  // namespace robot_specs\n'''


def render_ros(specs: dict, values: dict) -> str:
    r, c, comm = specs["robot"], specs["control"], specs["communication"]
    return f'''# AUTO-GENERATED by scripts/generate_robot_config.py. DO NOT EDIT.\nmoebius_base_driver:\n  ros__parameters:\n    port: {comm['default_port']}\n    baudrate: {int(comm['baudrate'])}\n    drive_type: mecanum\n    wheel_radius: {r['wheel_radius_m']:.6f}\n    wheelbase: {r['wheelbase_m']:.6f}\n    track_width: {r['track_width_m']:.6f}\n    ticks_per_revolution: {values['counts_per_wheel_revolution']}.0\n    max_wheel_rpm: {specs['motor']['rated_output_rpm']:.6f}\n    max_linear_velocity: {r['max_linear_velocity_mps']:.6f}\n    max_lateral_velocity: {r['max_lateral_velocity_mps']:.6f}\n    max_angular_velocity: {r['max_angular_velocity_rps']:.6f}\n    publish_tf: false\n    command_timeout: {c['command_timeout_ms'] / 1000.0:.3f}\n    serial_timeout: 0.05\n'''


def render_xacro(specs: dict, values: dict) -> str:
    r = specs["robot"]
    return f'''<?xml version="1.0"?>\n<!-- AUTO-GENERATED by scripts/generate_robot_config.py. DO NOT EDIT. -->\n<robot xmlns:xacro="http://www.ros.org/wiki/xacro">\n  <xacro:property name="wheel_radius" value="{r['wheel_radius_m']:.6f}"/>\n  <xacro:property name="wheel_diameter" value="{r['wheel_diameter_m']:.6f}"/>\n  <xacro:property name="wheelbase" value="{r['wheelbase_m']:.6f}"/>\n  <xacro:property name="track_width" value="{r['track_width_m']:.6f}"/>\n  <xacro:property name="counts_per_wheel_rev" value="{values['counts_per_wheel_revolution']}"/>\n</robot>\n'''


def generate(check: bool) -> int:
    specs = load_specs()
    values = derived(specs)
    outputs = {
        HEADER_PATH: render_header(specs, values),
        ROS_PATH: render_ros(specs, values),
        XACRO_PATH: render_xacro(specs, values),
    }
    stale = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("Generated files are stale:")
        for path in stale:
            print(f"  - {path}")
        print("Run: python3 scripts/generate_robot_config.py")
        return 1
    print(f"counts_per_wheel_revolution={values['counts_per_wheel_revolution']}")
    print(f"meters_per_tick={values['meters_per_tick']:.9f}")
    print(f"theoretical_max_speed_mps={values['theoretical_max_speed_mps']:.6f}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if committed generated files are stale")
    return generate(parser.parse_args().check)


if __name__ == "__main__":
    raise SystemExit(main())
